version: '3.4'

services:
  fastapi:
    hostname: FastAPI
    build: ./services
    ports:
      - ${FASTAPI_PORT}:5000
    volumes:
      - ./services/app:/app
      - ./services/app/site-packages:/usr/local/lib/python3.10/site-packages/

  # db:
  #   image: postgres:11-alpine
  #   hostname: db
  #   restart: always
  #   volumes:
  #     - ./data/db:/var/lib/postgresql
  #   environment:
  #     POSTGRES_USER: ${DATABASE_USER}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_DB: ${DATABASE_NAME}

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - ${ADMINER_PORT}:8080
