version: '3.4'

services:
  fastapi:
    hostname: FastAPI
    build: ./services
    ports:
      - ${FASTAPI_PORT}:5000
    depends_on:
      - database
    volumes:
      - ./services/app:/app
      - ./services/app/site-packages:/usr/local/lib/python3.10/site-packages/

  database:
    image: postgres:11-alpine
    hostname: database
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
    - database
    ports:
      - ${ADMINER_PORT}:8080

networks:
  default:
    name: fastapi